name: DynaTech
author: ProfElements
contributors: [wickidcow]
description: A Slimefun addon with machines, tools, fluids, utilities, and optional addon integrations.
main: me.profelements.dynatech.DynaTech
website: https://github.com/wickidcow/SF_DynaTech
depend: [Slimefun]
softdepend: [ExoticGarden, InfinityExpansion, InfinityExpansion2, Gastronomicon]
version: ${project.version}
api-version: '1.21'
